config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    get 'login', to: redirect('/auth/azure_oauth2/'), as: 'login'
	get 'logout', to: 'sessions#destroy', as: 'logout'
	get 'auth/:provider/callback', to: 'sessions#create'
	get 'auth/failure', to: redirect('/')
	get 'home', to: 'home#show'
	get 'me', to: 'me#show', as: 'me'

	root to: "home#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	def self.find_or_create_from_auth_hash(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.fname = auth.info.first_name
			user.lname = auth.info.last_name
			user.email = auth.info.email
			user.save!
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  	helper_method :current_user, :get_door, :unlock, :iot_open, :iot_close
  	after_action -> { flash.discard }
  	  	
	def iot_open
  		sc = UDPSocket.new
		sc.send("o", 0, "192.168.10.76", 2800)
		sc.close
		puts "open"
  	end

  	def iot_close
  		Thread.new do
  			sleep(3)
	  		sc = UDPSocket.new
			sc.send("c", 0, "192.168.10.76", 2800)
			sc.close
			puts "close"
		end
  	end

	def authenticate
		redirect_to :login unless user_signed_in?
	end

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def get_door
		return Door.where({ id: ['1'] }).first
	end

	def unlock
		respond_to do |format|
			flash[:primary] = "Door opened for 3 seconds"
			format.js { render :file => "/me/unlock.js.erb" }
	        format.json
	        format.html { render :file => "/me/show.html.erb" } 
		end
	end

	def user_signed_in?
		# converts current_user to a boolean by negating the negation
		!!current_user
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def show
	end
end

app/controllers/me_controller.rb
class MeController < ApplicationController
	before_action :authenticate
	def show
		if params[:go] == "1"
			iot_open
			iot_close
			unlock
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		@user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
		session[:user_id] = @user.id
		redirect_to controller: 'me', action: 'show', go: '1'
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
	    case level
	    	when 'primary' then "alert alert-dismissable alert-primary"
	        when 'notice' then "alert alert-dismissable alert-info"
	        when 'success' then "alert alert-dismissable alert-success"
	        when 'error' then "alert alert-dismissable alert-danger"
	        when 'alert' then "alert alert-dismissable alert-danger"
			when 'warning' then "alert alert-dismissable alert-warning"
	    end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/me_helper.rb
module MeHelper
end

app/views/home/show.html.erb
<div id="outercard">
	<div class="card text-center" id="logincard">
		<div class="card-header">
			<h1>Sign-In</h1>
		</div>
		<div class="card-body">
			<div class="text-muted">using<br><br></div>
			<%= link_to "/auth/azure_oauth2", class: "btn btn-outline-primary" do %>
				<i class="fab fa-microsoft fa-4x"></i><h1>Azure</h1>
			<% end %>
		</div>
		<div class="card-footer text-muted">
	  	</div>
	</div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <% if value.class == Array %>
        <div class="<%= flash_class(key) %> flash-body-notice" id="flashdiv">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <% value.uniq.each do |message| %>
                <%= message %>
                </br>
            <% end %>
        </div>
    <% else %>
        <div class="<%= flash_class(key) %> flash-body-notice" id="flashdiv">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <%= value %>
        </div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qr</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/me/show.html.erb
<div id="memain">
	<% if !current_user %>
		<% current_user.attributes.each do |k, v| %>
			<b><%= k %>:</b> <%= v %> <br>
		<% end %>
	<% end %>
	<div class="card border-light mb-3">
	  	<div id="titlecont" class="card-body text-secondary text-center">
	  		<strong><%= current_user.fname %> <%= current_user.lname %></strong>
	  		<div class="text-muted"><%= current_user.email %></div><br>
	  		<%= link_to logout_path, class: "btn btn-outline-dark" do %>
				Logout
			<% end %>
	  	</div>
	</div>

	<div class="card border-light mb-3">
	  	<div id="titlecont" class="card-body text-secondary text-center">
			<div class="btn-group" role="group" aria-label="Basic example">
				<%= link_to me_path(go: 1), class: "btn btn-primary", data: { toggle: "tooltip", placement: "bottom"}, title: "Unlock", remote: true do %>
					<i class="fas fa-unlock fa-fw fa-2x"></i>
				<% end %>
			</div>
	  	</div>
	</div>
	<div class="alert-msg text-center" id="flashstat">
		<%= render "layouts/flash" %>
	</div>
</div>

app/views/me/unlock.js.erb
$('div#flashstat').html("<%= escape_javascript(render 'layouts/flash') %>")
$("div#flashdiv").delay(2000).slideUp(500, function(){
	$("div#flashdiv").alert('close');
});